name: DockerHub

on:
  push:
    branches: main 
  pull_request: 
    branches: main
  #schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    # - cron: '55 * * * *'   
   
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push latest
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          context: latest
          file: latest/Dockerfile
          push: true
          tags: docker.io/davalfher/rstudio-verse:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
